
project_id = "wprlkplzlhyrphbcaalc"

[functions.send-offer-plate-email]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.payment-link]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = false

[functions.payment-notification]
verify_jwt = false

[functions.sendgrid-stats]
verify_jwt = false

[functions.sendgrid-activity]
verify_jwt = false

[functions.sendgrid-send]
verify_jwt = false
