
project_id = "wprlkplzlhyrphbcaalc"

[functions.payment-notification]
verify_jwt = false

[functions.payment-link]
verify_jwt = true

[functions.sendgrid-stats]
verify_jwt = true

[functions.sendgrid-activity]
verify_jwt = true

[functions.send-quote-email]
verify_jwt = true

[functions.sendgrid-send]
verify_jwt = true
